### PR TITLE
Re-add suseImportBuildKey

### PR DESCRIPTION
**Pull request by dcermak**
`suseImportBuildKey` is not required during the image build as kiwi imports the
correct keys by itself. However, the created images lack the repository signing
keys and any `zypper` commands will thus fail.

This fixes https://github.com/OSInside/kiwi/issues/1876

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
This seems more like we're doing the wrong thing for configuring repos. We shouldn't rely on this for Zypper to work correctly.

**Comment by dcermak** [comment]
> This seems more like we're doing the wrong thing for configuring repos. We shouldn't rely on this for Zypper to work correctly.

That is correct. But once the version of kiwi without suseImportBuildKey lands in Factory, it will break a lot of appliance builds in a subtle way. So I'd propose that we first restore the old behavior and then fix it properly, before we break a lot of appliances on OBS.

**Comment by Conan-Kudo** [comment]
> > This seems more like we're doing the wrong thing for configuring repos. We shouldn't rely on this for Zypper to work correctly.
> 
> That is correct. But once the version of kiwi without suseImportBuildKey lands in Factory, it will break a lot of appliance builds in a subtle way. So I'd propose that we first restore the old behavior and then fix it properly, before we break a lot of appliances on OBS.

Do you think that the appliances will actually get fixed unless they're broken first?

**Comment by schaefi** [comment]
I just don't understand why we need this code when this here:

```
--gpg-auto-import-keys  Automatically trust and import new repository
                            signing keys.
```

is expected to do exactly that, or am I completely wrong with this assumption ? We call zypper with that option and my expectation was that it does what the script here does

**Comment by dcermak** [comment]
> I just don't understand why we need this code when this here:
> 
> ```
> --gpg-auto-import-keys  Automatically trust and import new repository
>                             signing keys.
> ```
> 
> is expected to do exactly that, or am I completely wrong with this assumption ? We call zypper with that option and my expectation was that it does what the script here does

Because `suseImportBuildKey` inserts the rpm signing keys into the final image at build time. So if you invoke zypper inside the final image, it "just works". Without this function, **everyone** will have to add the `--gpg-auto-import-keys` flag later on and they should actually check that zypper fetched the correct keys…

That's imho a pretty bad UX if you ask me.

**Comment by Vogtinator** [comment]
Yeah, `suseImportBuildKey` needs to stay as-is at least for now. `gpg-auto-import-keys` is not an alternative at all, it makes it highly insecure because it just accepts whatever key the repository has without any checks at all!

> This seems more like we're doing the wrong thing for configuring repos. We shouldn't rely on this for Zypper to work correctly.

The `openSUSE-build-key` package contains the GPG keys for repos and packages, but doesn't import them on installation.

**Comment by Vogtinator** [comment]
> I just don't understand why we need this code when this here:
> 
> ```
> --gpg-auto-import-keys  Automatically trust and import new repository
>                             signing keys.
> ```
> 
> is expected to do exactly that, or am I completely wrong with this assumption ? We call zypper with that option and my expectation was that it does what the script here does

If you pass that to zypper in OBS, then it won't actually do anything because the local package repos in the build root are not signed.

**Comment by Conan-Kudo** [comment]
> Yeah, `suseImportBuildKey` needs to stay as-is at least for now. `gpg-auto-import-keys` is not an alternative at all, it makes it highly insecure because it just accepts whatever key the repository has without any checks at all!
> 
> > This seems more like we're doing the wrong thing for configuring repos. We shouldn't rely on this for Zypper to work correctly.
> 
> The `openSUSE-build-key` package contains the GPG keys for repos and packages, but doesn't import them on installation. That's what `suseImportBuildKey` currently does.

**Comment by Conan-Kudo** [comment]
We also don't specify the GPG key file in the manifest, which would be ideal for resolving this properly. I generally don't like the idea of just mass-importing keys...

**Comment by schaefi** [comment]
> Yeah, suseImportBuildKey needs to stay as-is at least for now.

ok, so let's not mess with it, get back to the working state and revisit this topic on the community meeting. I think it's pretty odd if the install of a key package has no effect and is also not effectively used by the package manager unless there is some extra code moving the bits around. Anyway I'll merge this here, thanks much @dcermak and maybe someone can explain the deeper design aspects of the build key provision at the meeting next week

**Pull request merged**
