### PR TITLE
Added microdnf integration test

### PR DESCRIPTION
**Pull request by schaefi**
Add an integration test for the recently added microdnf support

### CODE REVIEW

**Comment by schaefi** [comment]
Please find the test build here

* https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:fedora/test-image-microdnf

**Comment by Conan-Kudo** [comment]
cc: @dmach, @tabowling, @sysrich, @lkocman

**Comment by Conan-Kudo** [comment]
> Please find the test build here
> 
> * https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:fedora/test-image-microdnf

@schaefi It looks like the build is failing for unrelated reasons?

```
[  253s] [ DEBUG   ]: 15:35:11 | EXEC: [jing /usr/lib/python3.9/site-packages/kiwi/schema/kiwi.rng /tmp/xslt-cckh1f4t]
[  253s] [ DEBUG   ]: 15:35:11 | "jing": in paths "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin" exists: "False" mode match: not checked
[  253s] [ DEBUG   ]: 15:35:11 | EXEC: Command "jing" not found in the environment
```

**Comment by schaefi** [comment]
#1626 must be merged to get this running

**Comment by Conan-Kudo** [comment]
@schaefi I merged #1626 so this needs to be rebased.

**Comment by schaefi** [comment]
nope, no rebase needed, a new python-kiwi in Staging is needed. I will submit it

**Comment by schaefi** [comment]
```
[  353s] [ DEBUG   ]: 16:00:08 | EXEC: [bash -c microdnf --refresh --config /usr/src/packages/KIWI-oem/build/image-root/tmp7ryv05mv -y --installroot /usr/src/packages/KIWI-oem/build/image-root --setopt=install_weak_deps=False install basesystem filesystem grub2-efi-x64 grub2-efi-x64-modules microdnf shim]
[  353s] [ INFO    ]: Processing: [                                        ] 0%
[ INFO    ]: Processing: [########################################] 100%
[  353s] [ ERROR   ]: 16:00:08 | KiwiBootStrapPhaseFailed: Bootstrap package installation failed: error: (--setopt) Invalid boolean value "False" in: install_weak_deps=False
```

@Conan-Kudo ?

**Comment by Conan-Kudo** [comment]
@schaefi Blech, microdnf only accepts `0` (off) `1` (on)

**Comment by Conan-Kudo** [comment]
@schaefi Fixed with #1628.

**Comment by schaefi** [comment]
Thanks for the fix, now the next complain

```
[  131s] [ ERROR   ]: 09:50:16 | KiwiBootStrapPhaseFailed: Bootstrap package installation failed: error: The "--installroot" argument must be used together with "--config", "--noplugins", "--setopt=cachedir=<path>", "--setopt=reposdir=<path>", "--setopt=varsdir=<path>" arguments.
[  131s] 
```

**Comment by Conan-Kudo** [comment]
Hopefully that should be fixed with the merge of #1630.

**Comment by schaefi** [comment]
All fixed now and the integration test builds and boots :smiley:

**Pull request merged**
