### PR TITLE
package: adjust openSUSE patch

### PR DESCRIPTION
**Pull request by aplanas**
Add the openSUSE patch as a `Patch1` element, and set `%autosetup` to `-p1`

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
This commit means that SRPMs now can conditionally be broken by not including the patch. I did it differently _on purpose_ to avoid that.

**Comment by aplanas** [comment]
> This commit means that SRPMs now can conditionally be broken by not including the patch. 

The patch is under a macro guard. Would not this resolve this issue?

> I did it differently _on purpose_ to avoid that.

Right, the problem is that the Factory / OBS packaging policies[1] require certain properties for a patch: needs to be referenced as a "Patch:", needs to be in the changelog, and optionally tagged.

[1] https://en.opensuse.org/openSUSE:Packaging_Patches_guidelines

**Comment by Conan-Kudo** [comment]
Macro guards are the problem. That's not allowed for `Patch` or `Source` because it means the SRPM can be generated in a way that's broken.

**Comment by aplanas** [comment]
Without breaking the policy (that makes the submission automatically declined), what can be a good solution then? Maybe creating a different spec template only for openSUSE?

**Comment by aplanas** [comment]
Maybe unconditionally add the patch in the spec file, remove the autosetup and manually apply the patch with "%patch"? That seems a bit of step backwards to me (I like autosetup)

**Comment by Conan-Kudo** [comment]
I like autosetup too, but `%autosetup -N` and `%autosetup -m/-M` aren't supported everywhere so we have to roll back a bit.

https://github.com/OSInside/kiwi/pull/2556

**Pull request merged**
