### PR TITLE
 Return failure if overlay is not supported

### PR DESCRIPTION
**Pull request by LaszloGombos**

### CODE REVIEW

**Comment by schaefi** [comment]
@LaszloGombos Hi, thanks for the change. I agree it looks like dead code. But just to put me right, how did you stumble over it ? did it cause an issue in some way ? I guess not.

We are usually pretty picky on initrd code changes and there was no description on the PR, that's why I'm asking

Thanks

**Comment by schaefi** [comment]
@davidcassany as usual another pair of eyes should look at this as well. For me this is fine and I would just merge it

**Comment by schaefi** [comment]
of course shellcheck complain should be fixed

**Comment by LaszloGombos** [comment]
> how did you stumble over it

I was working on dracut and reviewing out-of-tree dracut modules (https://github.com/dracutdevs/dracut/wiki/Dracut-development#projects-with-out-of-tree-dracut-modules) for consistency. 

> did it cause an issue in some way
No it did not cause any issue for me. I suspect this discussion is about proper error handling (and not about happy code path functionality) and I am not in a position to run some of these negative test to see if they are handled properly.

> We are usually pretty picky on initrd code changes
As you should be :-) I changed the direction of this PR to the opposite of the original PR :-) 

> of course shellcheck complain should be fixed
Not able to see them for the updated PR as I am a first time contributor :-)  If I find time I will try to run them locally.

**Comment by davidcassany** [comment]
the change makes complete sense to me, thanks @LaszloGombos 

> I was working on dracut and reviewing out-of-tree dracut modules (https://github.com/dracutdevs/dracut/wiki/Dracut-development#projects-with-out-of-tree-dracut-modules) for consistency.

Interesting wiki, I was not aware of it, gonna go through it.

**Review by davidcassany — APPROVED** [review]

**Comment by schaefi** [comment]
yep looks all great now, thanks :+1: Also looking at the projects-with-out-of-tree-dracut-modules docs, thanks for sharing

**Pull request merged**
