### PR TITLE
Update tox and travis setup for python 3_8

### PR DESCRIPTION
**Pull request by schaefi**
Move latest python test target to 3.8 and also change
the deploy travis target to use python 3.8

### CODE REVIEW

**Comment by schaefi** [comment]
I realized the pypi deployment on travis requires python 3.8 to operate. That's why this change was made. I also think we should move the latest python test target to 3.8

**Comment by davidcassany** [comment]
> I realized the pypi deployment on travis requires python 3.8 to operate. That's why this change was made. I also think we should move the latest python test target to 3.8

Yes I agree and python 3.8 is also the current python3 version for TW.

**Review by davidcassany — APPROVED** [review]
I have no strong arguments to increase or decrease the complexity level of the flake check. Having it low can be helpful when coding big chunks of code to enforce us to try to split it with as many as possible meaningful pieces. However I also believe human reviews are the best way to keep code maintainable and readable, so I don't have the impression that we will lower the code quality by relaxing complexity limit of flake rules.

**Comment by schaefi** [comment]
>I also believe human reviews are the best way to keep code maintainable and readable, so I don't have the impression that we will lower the code quality by relaxing complexity limit of flake rules.

Right that's what I also think

**Pull request merged**
