### PR TITLE
Drop isolinux

### LINKED ISSUE #2433: Drop SYSLINUX/ISOLINUX support
## Problem description

SYSLINUX has been abandoned for several years now, and it does not even work with modern versions of the filesystems supported in SYSLINUX. Thus, we should drop our support for ISOLINUX (we already dropped support for SYSLINUX in 2016 in 8217431c7eb0172b37c15f6e0b3772cb4af8ae1a).

### PR DESCRIPTION
**Pull request by schaefi**
Drop support for syslinux/isolinux
    
SYSLINUX has been abandoned for several years now, and it does not even work with modern versions of the filesystems supported in kiwi. This commit drops it and Fixes #2433

### CODE REVIEW

**Comment by schaefi** [comment]
@Conan-Kudo a big change again and please don't merge until I create a Staging release to see what image builds break by this. Thanks

**Comment by Conan-Kudo** [comment]
Sure.

**Comment by Conan-Kudo** [comment]
This needs rebasing since it now conflicts with mainline. Also, what was the outcome of staging runs?

**Comment by schaefi** [comment]
> This needs rebasing since it now conflicts with mainline. Also, what was the outcome of staging runs?

I'm on it, I waited for Dan on the other PR which is now merged. I will fix the conflicts here and zip a new Staging release from this PR to see what breaks, stay tuned

**Comment by schaefi** [comment]
Build tests are running... I'll check them over the weekend

**Comment by schaefi** [comment]
tests are good

**Pull request merged**
