### PR TITLE
Post-build config concept

### PR DESCRIPTION
**Pull request by isbm**
This is a concept of post-build config. The basic idea is that it is as same as `config.sh`, except it is called after everything is already on the image. Mostly this is useful for the embedded. Currently this is working on "root" only, so I think should be expanded to something like `bootloader-post-build.sh`, `root-post-build.sh` etc.

Ideas/suggestions/criticism encouraged.

*Upd*: It also helps #1464

P.S. I also started slowly adding annotations, because it is easier then to work with. It also would be nice if you, guys, decide on a standard code formatter (linting), because it is pain to work with modern Python editors, those now tends to enforce code formatting in Go fashion and then [this happens](https://github.com/OSInside/kiwi/pull/1465/commits/e2759c5471a466778eb4991ceedc313cb45489df).

### CODE REVIEW

**Comment by schaefi** [comment]
Hey thanks for all your effort. Before I share my view on the suggested proposal let me comment
on the following:

>P.S. I also started slowly adding annotations, because it is easier then to work with. It also would be nice if you, guys, decide on a standard code formatter (linting), because it is pain to work with modern Python editors, those now tends to enforce code formatting in Go fashion

I think we are following the standard of the flake8 linter which is also running on every PR. See testenv:check in tox.ini. From my perspective this a good standard for python projects. Do you think this is not the case ?

If editors like code enforce something different this should be imho solved on the level of the editor setup and not by changing the code here to make the editor happy. Especially the rule enforcement of go applied to python is in my opinion questionable. The extra newlines as
well as the change of 80c lines to long lines in the scope of this PR makes it harder to review the code. If you don't mind if would be good to turn that back such that we can focus on the actual changes. Would that be possible ?

I admit the 80c lines is something I personally like because it makes reading code easy and it prevents over complicated code on one liners. I know there are people who see that differently 
and I respect that which is why we allow long lines, see setup.cfg "ignore = E501" from the linter. However the code I wrote in this project follows 80c lines and it would be nice if people respect that part when I also respect lone lines from other peoples contributions.

Overall I think the review of your idea will be easier without the linter changes as a start

**Comment by schaefi** [comment]
Regarding the idea of a script that runs after the system gets transfered into the actual image loop disk. I like that idea and there are also other people who had this use case in the past. Two things on the current implementation which I'd like to discuss is

a) you said this script is the same than config.sh just called at another place in the process. This is only partial correct because config.sh is called in any case for all image types at the end of the creation of the root data. Your script is specific to the disk builder and also runs as part of the loop disk data. This means the modification the script hook does are not permanent to the image root data. This is not a problem but the script hook should indicate that clearly by its name and we also need to have that documented

b) the implementation of the script hook actively mounts the rootfs, this should not be done because the full mount of the system is not known to you at this point. A system can have an extra boot partition, it could have lvm volumes, it could have btrfs sub-volumes, it could be luks layered it could be raid layered etc etc... So what mounting of the system means should not be an action you do prior calling the script. If you look at the disk builder code you will find ```sync_data(``` calls. At this point the system is in the mount state you are after and right before the bootloader gets installed you can include the script call as chrooted operation in whatever device_map['root'] defines.

Does this makes sense ?

**Comment by schaefi** [comment]
I also looked at the code that syncs the root data to the disk. There is a little inconsistency between the FileSystem class and the VolumeManager class. The first populates self.filesystem_mount
whereas the last has self.mountpoint. I suggest a little refactoring PR and will look into it

**Comment by isbm** [comment]
Due to a) -- yes, absolutely. With b) -- that's why a big thanks for clarifying! Yes, I wasn't that sure exactly on that part, and that's currently more a try/hack than something final (hence I don't care ATM of broken tests). Also user would like _maybe_ also to do something else with other partitions, so currently I was experimenting with root only and hammering only active mount. Originally I thought that the system is mounted, but then I found it is not. Yes, I was looking exactly that `sync_data` part, I will try look into that in a minute and get back here.

**Comment by schaefi** [comment]
> Yes, I was looking exactly that sync_data part,

perfect. we need a little refactoring to make that usable for your use case. Let me code that and I will send a PR. Also @davidcassany feedback is very much welcome

**Comment by isbm** [comment]
> inconsistency between the FileSystem class and the VolumeManager class.

We will make it perfect. Let's do one step at a time: first proper concept, then proper interface with the usage, then polish/fix tests. Sounds like a plan?

P.S. Please think of MyPy in tox and annotations. I am using it all the time and it does help a lot (and this code needs it).

**Comment by schaefi** [comment]
yep good plan

**Comment by isbm** [comment]
@schaefi hm, now I remember. I actually been there already and it doesn't work (hence the mentioned Issue I've opened): dracut, bash etc, now I have that problem back. The very idea of the post-build is to do whatever needed after all other tooling done (dracut including). And that's quite important.

Any other ways to mitigate that? I am even OK to go after different types of remounts, if I need to, but generally I am not just after mounted system, but after "finished state of building before final image bake" state.

**Comment by isbm** [comment]
> A system can have an extra boot partition, it could have lvm volumes, it could have btrfs sub-volumes, it could be luks layered it could be raid layered etc etc...

I was thinking to get the constraints first:
- Embedded and Btrfs do not match (rare exceptions, but you want to avoid that, if possible). So I would rather less worry about this part at this point.
- This is "advanced mode" and mostly manual at this point with intention "you know what you are doing". The very purpose of it is to undo what distribution did (e.g. remove zypper, libsolv, cracklib and other packages you never need in embedded, replace coreutils etc etc). So it is more like "shaping up" OS image with a final touch.
- Its main purpose for the finished rootfs alteration, something that normally nobody does it in a regular appliance mode.

So maybe we can go with active remounts after all and then just restrict it to specific file systems, reading the layout from the `config.xml` and/or collect that data before? I would be willing helping even to extend the "mount awareness" so the remount is correct then.

Ideas?

**Comment by davidcassany** [comment]
The idea of having some hook that is chrooted into the disk looks reasonable to me. At the moment I fail to see if this has some potential for being used in other environments beyond disks (filesystem images, container trees, etc.), but I doubt it. Thus as it has been already said we should make explicit the scope of this feature.

Feature wise my only concern is the proliferation of hooks were the user is getting more chances to miss use it. I see we have `config.sh`, `images.sh`, boot scripts and now probably something like `disk-config.sh`. I'd say this is still maintainable, but still quite a few.

> Embedded and Btrfs do not match (rare exceptions, but you want to avoid that, if possible). So I would rather less worry about this part at this point.

Well, not so sure, probably not for the embedded plus btrfs tandem, but we should consider complex configurations as it is done for MicroOS images.

> The very purpose of it is to undo what distribution did (e.g. remove zypper, libsolv, cracklib and other packages you never need in embedded, replace coreutils etc etc). 

Note that we have this other opened issue to this sort of procedures #915 and our major issue in there is precisely that removing zypper and rpm stack can't be done easily done from a chrooted env. 

> I would be willing helping even to extend the "mount awareness" so the remount is correct then.

I like the idea of thinking of utilities to properly mount the disk device to chroot in it. I haven't had a close look though not sure right now how far we are or how difficult it is, I'd also like to avoid major refactors.

@isbm out of curiosity, which is the use case to remove busybox, coreutils and staff like that? Is it just a matter of space saving? Just trying to understand the underlying needs

**Comment by isbm** [comment]
> out of curiosity, which is the use case to remove busybox

Ah. No. "Replace coreutils with busybox" -- sorry! (corrected comment too).

**Comment by schaefi** [comment]
#1469 offers a way to run a disk.sh script from your image description inside of the fully loop mounted disk. I think this should serve the purpose regarding the actions you need. If the PR is acceptable I can submit a package to https://build.opensuse.org/project/show/Virtualization:Appliances:Staging from you can give it a try as well.

**Comment by isbm** [comment]
I am not sure how that supposed to work:

1. Create `disk.sh` inside description.
2. Call build:

```
[ ERROR   ]: 13:43:31 | KiwiScriptFailed: disk.sh failed: chroot: failed to run command ‘/image/disk.sh’: No such file or directory
```

If I delete that script, no problems then. :wink:

**Comment by schaefi** [comment]
Hmm, it worked in my test but I can reproduce the error you got too in another test. Still investigating...

**Comment by schaefi** [comment]
found it :) btrfs related, the get_mountpoint method must be handled correctly for the btrfs volume manager like it's done for sync_data in this case. I missed that part. Will fix it in a minute

**Comment by schaefi** [comment]
@isbm ok fixed now. Please find packages in https://build.opensuse.org/project/show/Virtualization:Appliances:Staging and also see the integration test for this running here: https://build.opensuse.org/package/show/Virtualization:Appliances:Images:Testing_x86:suse/test-image-oem. It should turn to green as soon as the new package is done.

Thanks for testing

**Comment by schaefi** [comment]
I think this one can be closed on behalf of #1469 

if not feel free to re-open

**Pull request closed without merging**
