### PR TITLE
Use GPT table for Power ofw firmware

### PR DESCRIPTION
**Pull request by schaefi**
GPT partition table should be preferred for power systems these days

### CODE REVIEW

**Comment by schaefi** [comment]
I have to double check if this is the correct partition ID for the prep partition

```
   1            2048            4095   8.0 MiB     4100  p.prep
```

**Comment by schaefi** [comment]
should be ok

**Comment by schaefi** [comment]
The obs oem build also succeeded

**Comment by davidcassany** [comment]
@schaefi Oh sorry I did not include my approval into the PR as I was waiting for the confirmation on partition ID, just in case there was a further commit.

**Pull request merged**
