### PR TITLE
Added a NOTE: section to explain the finer points of adding tools for a hook script

### PR DESCRIPTION
**Pull request by jbmixer**
This is a documentation change ONLY. One file changed. I added a note below the description of creating a dracut hook for Kiwi imaging.  Please review the added Note section.

Changes proposed in this pull request:
* More detail when adding additional tools needed to run the dracut hook script

### CODE REVIEW

**Review by schaefi — APPROVED** [review]
Thanks much looks great :+1:

**Comment by jbmixer** [comment]
Sorry, didn't mean to request a comment. This is not still in progress.   I'm happy with the change if you are. Where (or how) to take it from here?

**Comment by schaefi** [comment]
> Sorry, didn't mean to request a comment. This is not still in progress. I'm happy with the change if you are. Where (or how) to take it from here?

From my perspective this looks good and can be merged as a first change set. You said you consider it not complete ? That's ok I think this is a first iteration which can be merged and you can add more on top of it

**Comment by schaefi** [comment]
BTW: usually tests has to pass but this one is not happening because of your changes. It was caused due to an update of flake which is now more strict on checking the code. Thus I'm going to merge your doc extensions and send a big thanks :) More of it is very much appreciated

**Comment by schaefi** [comment]
on a personal note, I recommend you to sign your commits. See

* https://osinside.github.io/kiwi/contributing.html?highlight=signing#signing-git-patches

**Comment by jbmixer** [comment]
Thanks Marcus. I thought I had signed my commit. I have created a signing key and executed "git commit -S -a" to commit the change. It asked me for my signing ID and name before it committed. I must have done something wrong. I will have more pull requests in the future (I hope!) and more questions on the Google group.

**Pull request merged**
