### PR TITLE
Add support for the Micro DNF package manager

### PR DESCRIPTION
**Pull request by Conan-Kudo**
Micro DNF is a minimal C implementation of DNF that is usable for
minimal appliances and containers. While it is not at parity with
DNF, it implements enough functionality that it is mostly usable
for building appliance images.

Changes proposed in this pull request:
* Add support for using Micro DNF for building appliance images

### CODE REVIEW

**Comment by Conan-Kudo** [comment]
cc: @dmach, @sysrich, @lnussel

**Comment by Conan-Kudo** [comment]
cc: @lkocman @tabowling

**Comment by schaefi** [comment]
@Conan-Kudo great job :+1: this looks really clean to me. I will add microdnf to the universal box and will run a test.
dnf and microdnf can co-exist correct ?

**Comment by Conan-Kudo** [comment]
@schaefi Yes, they can!

**Pull request merged**
