### PR TITLE
Use 'source' instead of 'configfile' in generated grub.cfg

### LINKED ISSUE #2320: Grub menu problem with live isos in EFI mode
## Problem description

When I press Esc in the top level grub menu of leap/tumbleweed live isos booted in EFI mode, grub shell screen is shown without an evident way to get back to the menu

## Expected behaviour

Esc in the top level grub menu in EFI mode should do nothing, like when the same iso is booted in BIOS mode.

## Steps to reproduce the behaviour

- create a new EFI vm
- attach a leap/tumbleweed live iso to it. I tried leap 15.5 and tumbleweed 20230705
- power the vm up, wait for grub menu to appear
- press Esc
- try to get back to the menu like press Esc once more

Repeat it in a BIOS vm and notice there is no such problem.

## OS and Software information

* KIWI version: the problem supposedly dates back to this commit https://github.com/OSInside/kiwi/commit/3255264d4c57678c2f6cd5b1243de340e76230ed
* Operating system host/target version: irrelevant

## Research

The origin of the problem are these lines:

https://github.com/OSInside/kiwi/blob/16a703cd98b8c543bb5e2848e7b5203275472a09/kiwi/bootloader/config/grub2.py#L1078

https://github.com/OSInside/kiwi/blob/16a703cd98b8c543bb5e2848e7b5203275472a09/kiwi/bootloader/config/grub2.py#L1099

Was there any particular reason to use `configfile` instead of `source` there? With `source` the problem goes away: the top level menu is not nested into some scope, there is nowhere to return with Esc, hence it does nothing.

shim-install also creates such transit grub config and it uses `source`:

```
428 cat <<EOF
429 search --fs-uuid --set=root ${cfg_fs_uuid}
430 set prefix=(\${root})`${grub_mkrelpath} ${grub_cfg_dirname}`
431 source "\${prefix}/${grub_cfg_basename}"
432 EOF
```

### PR DESCRIPTION
**Pull request by slowpeek**
Fixes #2320

### CODE REVIEW

**Comment by slowpeek** [comment]
I see the problems with the tests. Fixing it ..

**Comment by slowpeek** [comment]
The checks should pass this time but I rebased one extra commit, will fix it

**Comment by slowpeek** [comment]
Looks good now

**Comment by schaefi** [comment]
yep looks good, I'd like to have @davidcassany and @Conan-Kudo to take a look at this one too. Thanks

**Review by Conan-Kudo — APPROVED** [review]
Seems fine to me.

**Comment by marcan** [comment]
FYI, this creates a timebomb with Fedora/RH installs that explodes on the next GRUB update: https://bugzilla.redhat.com/show_bug.cgi?id=2235692

I don't consider this a Kiwi bug, but you should be aware since I expect more than just Asahi Linux users are affected.

**Pull request merged**
