### PR TITLE
Move util linux dep

### PR DESCRIPTION
**Pull request by dcermak**
Fixes dependency issues reported in https://github.com/OSInside/kiwi-functional-tests/issues/8.

### CODE REVIEW

**Comment by dcermak** [comment]
With this change:
```ShellSession
❯ rpm -qR /var/tmp/build-root/openSUSE_Tumbleweed-x86_64/.mount/.build.packages/RPMS/x86_64/dracut-kiwi-lib-9.23.40-0.x86_64.rpm
/bin/bash
bc
btrfsprogs
coreutils
cryptsetup
curl
device-mapper
dialog
e2fsprogs
gptfdisk
grep
lvm2
mdadm
parted
pv
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
util-linux
util-linux-systemd
xfsprogs
xz

🏠/packages/obs/Virtualization:Appliances:Staging/python-kiwi
❯ rpm -qR /var/tmp/build-root/openSUSE_Tumbleweed-x86_64/.mount/.build.packages/RPMS/x86_64/dracut-kiwi-live-9.23.40-0.x86_64.rpm
/bin/bash
device-mapper
dialog
dracut
e2fsprogs
parted
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1
util-linux
util-linux-systemd
xfsprogs
xorriso

🏠/packages/obs/Virtualization:Appliances:Staging/python-kiwi
❯ rpm -qR /var/tmp/build-root/openSUSE_Tumbleweed-x86_64/.mount/.build.packages/RPMS/x86_64/dracut-kiwi-oem-dump-9.23.40-0.x86_64.rpm
/bin/bash
dracut-kiwi-lib = 9.23.40-0
gawk
kexec-tools
kpartx
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1

🏠/packages/obs/Virtualization:Appliances:Staging/python-kiwi
❯ rpm -qR /var/tmp/build-root/openSUSE_Tumbleweed-x86_64/.mount/.build.packages/RPMS/x86_64/dracut-kiwi-oem-repart-9.23.40-0.x86_64.rpm
/bin/bash
dracut-kiwi-lib = 9.23.40-0
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1

🏠/packages/obs/Virtualization:Appliances:Staging/python-kiwi
❯ rpm -qR /var/tmp/build-root/openSUSE_Tumbleweed-x86_64/.mount/.build.packages/RPMS/x86_64/dracut-kiwi-overlay-9.23.40-0.x86_64.rpm
/bin/bash
dracut
dracut-kiwi-lib = 9.23.40-0
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsZstd) <= 5.4.18-1

```

**Comment by davidcassany** [comment]
At glance it looks good, let me prepare a build env with it IBS we can verify for all relevant SUSE based distros.

**Review by schaefi — APPROVED** [review]
Perfect thanks much :+1:

**Comment by davidcassany** [comment]
Oh all this is quite confusing, I just checked utils-linux and utils-linux-systemd packages and they are basically a link of each other in all distros I checked SLE/Leap 15.1/15.2/15.3 and TW. This is quite confusing since they have different specs thus same sources produce different set of binaries, I don't really see why this approach is needed I find it quite confusing (why not subpackaging?).

Anyway from that I only can say requiring both in every distro is safe. Which brings me to the point that starting from SP3 or 15.3 this not only safe but required.

So the change done here needs to be backported to SP3 and 15.3, I am surprised it did not popup there yet. I have not tested, in a KIWI build, but I just verified util-linux does not provide lsblk in SP3... :disappointed:

**Pull request merged**
