### PR TITLE
Refactor factory classes

### LINKED ISSUE #1498: Refactor Factory Classes
## Problem description

The way Factories are implemented in kiwi is from a strong typed API perspective
questionable and can be done more clear and stable like it was done in #1495 

In addition to the FileSystem factory the following other factory classes needs
adaption:

- [x] builder
- [x] boot/image
- [x] bootloader/config
- [x] bootloader/install
- [ ] container
- [ ] container/setup
- [x] filesystem
- [ ] iso_tools
- [x] markup
- [ ] oci_tools
- [x] package_manager
- [x] partitioner
- [x] repository
- [x] solver/repository
- [x] storage/subformat
- [x] system/root_import
- [x] volume_manager

### PR DESCRIPTION
**Pull request by davidcassany**
This PR finally makes the factory refactor complete.

Fixes #1498

### CODE REVIEW

**Comment by schaefi** [comment]
@davidcassany you probably have to wait for the doc fix to be merged for the pipeline to succeed

**Comment by davidcassany** [comment]
> @davidcassany you probably have to wait for the doc fix to be merged for the pipeline to succeed

Sure, in any case I realized I forgot to commit my last little changes to get 100% coverage on unit tests.

**Comment by schaefi** [comment]
> > @davidcassany you probably have to wait for the doc fix to be merged for the pipeline to succeed
> 
> Sure, in any case I realized I forgot to commit my last little changes to get 100% coverage on unit tests.

That just tells us testing works as expected :-)

**Comment by schaefi** [comment]
@davidcassany I rebased your branch with master to pull in the doc fixes that prevented the pipeline to succeed

**Review by schaefi — APPROVED** [review]
Looks great :+1: Thanks much

**Pull request merged**
