### PR TITLE
Refactor host system dependencies into individual subpackages

### LINKED ISSUE #1503: Packaging
## Problem description

Among other dubious deps, `zypper install python3-kiwi` asks also these dependencies:

```
bea-stax
bea-stax-api
git-gui
gitk
java-11-openj9-headless
javapackages-filesystem
javapackages-tools
timezone-java
tk
```

My instance:
```
cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="15.2 Beta"
```

So seems like not "just Python", but also "git-gui" and "tk" with "java"... :-) Overall, about 200Mb installation. I'd say, it is a bit of too much, no?

### PR DESCRIPTION
**Pull request by Conan-Kudo**
Fixes #1503.

Changes proposed in this pull request:
* Minor cleanups of dependencies
* Rework of system dependencies to split out into subpackages

### CODE REVIEW

**Comment by schaefi** [comment]
I did a review even though you indicated not to merge. Here is what I found

> kiwi-schema = 7.2

Should be changed to kiwi-schema = 7.3

The following Provides tag is missing:

* Provides:       kiwi-image:tbz

This should come with the main package, building a tarball from the root tree is the most simple image one can build and only requires tar which is set in the master package

Thanks

**Comment by Conan-Kudo** [comment]
@schaefi Yeah, I intended for this to be reviewed and tested *before* merging, because this is a massive refactor of the packaging.

**Comment by Conan-Kudo** [comment]
Also, there's functionality in kiwi that I didn't know existed before now that I need to package for Fedora (WSL image builds).

**Review by schaefi — APPROVED** [review]
From my perspective this looks great :+1: 

If we all agree I would create a package and submit it to Staging. From there we will see how obs behaves on the build of the integration tests. If everything works as expected this is good to go. Thoughts ?

**Comment by Conan-Kudo** [comment]
@schaefi Can you manually create a build branched from staging first? I want to see that we've got all the runtime deps satisfied. The amount of differences between SUSE and everything else makes me nervous...

**Comment by schaefi** [comment]
> @schaefi Can you manually create a build branched from staging first? I want to see that we've got all the runtime deps satisfied. The amount of differences between SUSE and everything else makes me nervous...

done here:

* https://build.opensuse.org/project/show/home:sax2:branches:Virtualization:Appliances:Staging

From my pov it looks good

**Comment by schaefi** [comment]
For Arch and Debian based there are no such kiwi-systemdeps-* packages. From the spec file I don't see that they are excluded. Maybe I'm overlooking something

**Comment by schaefi** [comment]
There is one complain:

```
obs://build.opensuse.org/home:sax2:branches:Virtualization:Appliances:Staging/Ce
ntOS_7/d5317019a2a3f1b418f4ad7cd3f81d43-python-kiwi'
/home/abuild/rpmbuild/SOURCES/python-kiwi.spec
[   75s] error: line 325: Unknown tag: Recommends:     kiwi-systemdeps =
9.22.1-3.1

```

**Comment by Conan-Kudo** [comment]
I did nothing for Arch, but Debian should have them, since the spec file defines it for both.

**Comment by schaefi** [comment]
> I did nothing for Arch, but Debian should have them, since the spec file defines it for both.

yes I see it for Debian, sorry. Arch doesn't have it but that's not a prio

**Comment by Conan-Kudo** [comment]
> There is one complain:
> 
> ```
> obs://build.opensuse.org/home:sax2:branches:Virtualization:Appliances:Staging/Ce
> ntOS_7/d5317019a2a3f1b418f4ad7cd3f81d43-python-kiwi'
> /home/abuild/rpmbuild/SOURCES/python-kiwi.spec
> [   75s] error: line 325: Unknown tag: Recommends:     kiwi-systemdeps =
> 9.22.1-3.1
> ```

This should be fixed now.

**Comment by schaefi** [comment]
yes is fixed, see the branch project

**Comment by Conan-Kudo** [comment]
@schaefi Thanks, I'm going to verify all the dependencies before giving my final assent to merge this.

**Review by davidcassany — APPROVED** [review]
Nice approach! looks good to me :+1: 

@schaefi @Conan-Kudo  whenever we test refactor of the spec in Staging I'd suggest to spend some time to clear the current project configs we have there. We should be capable to get rid of most of them.

**Comment by schaefi** [comment]
yes prjconfig cleanup should be a followup once the package is in Staging

**Comment by Conan-Kudo** [comment]
@schaefi This is ready to go, I've made image validation and container build runtime dependencies not mandatory for Debian/Ubuntu because it breaks installation.

**Pull request merged**
