### PR TITLE
Refactor grub2 config file setup

### PR DESCRIPTION
**Pull request by schaefi**
This is a big change. On a high level it does the following:

1. For disk based images the grub config file is being created by calling ```grub2-mkconfig```

2. It adapts the building of disk images if the kiwi initrd system is used instead of dracut.
    The required changes are divided into two extra commits

I'm afraid this is not easy to review because I also had to adapt the unit tests to follow our refactoring investment, For review I suggest to build oem and vmx images plus live and install images from our existing image descriptions. I did that and things worked nicely so far

Thanks much for review

### CODE REVIEW

**Comment by schaefi** [comment]
This references #1194

**Comment by schaefi** [comment]
gitlab failed with ```There has been a runner system failure, please try again``` The funny part is that there is no way to restart a pipeline. At least I haven't found any button ??

**Comment by davidcassany** [comment]
> gitlab failed with `There has been a runner system failure, please try again` The funny part is that there is no way to restart a pipeline. At least I haven't found any button ??

I happened to me too some time ago and I thought it was because I did not have the right permissions :P

**Comment by schaefi** [comment]
Thanks good point, the template contains unused data now. I'll delete the unused parts

**Comment by schaefi** [comment]
Thanks :) I'm so happy we can do refactoring

**Pull request merged**
