### PR TITLE
Fixed ovf Machine section setup for virtualbox

### LINKED ISSUE #1322: Vagrant boxes request the microphone with the Virtualbox provider
## Problem description

I was made aware in [boo#1157615](https://bugzilla.opensuse.org/show_bug.cgi?id=1157615) that the virtualbox vagrant boxes request the microphone which confuses users.

This does not occur with other vagrant boxes (that are usually built by packer), for instance the [Ubuntu 18.04 Bento box](https://app.vagrantup.com/bento/boxes/ubuntu-18.04). You can find the extracted Virtualbox ovf description [here](https://trello-attachments.s3.amazonaws.com/5d51288d62546874d4dbb916/5dce944cc886898f943f1b39/29bd4d0d9a7012c808197c79fe29791a/bento_box.ovf). According to the information that I've found online, turning of the microphone is tuned by this line:
``` xml
<AudioAdapter driver="ALSA" enabled="true" enabledIn="false" enabledOut="false"/>
```

This line is part of the `<vbox:Machine>` element, which we have completely omitted from the template in [kiwi/storage/subformat/template/virtualbox_ovf.py](https://github.com/osinside/kiwi/blob/master/kiwi/storage/subformat/template/virtualbox_ovf.py). However that element contains a lot of machine specific settings like the RAM size, CPU count, etc. so I am not sure if we should set these. On the other hand: basically every packer built box has such a section and for these it **is** possible to retroactively change the CPU count and so on.

Anyone has any experience with this? Opinions how we should fix this?

## OS and Software information
+ KIWI version: latest release
+ Operating system: any
+ OBS version: build.opensuse.org

### PR DESCRIPTION
**Pull request by schaefi**
Required attributes name and ostype were missing
according to IVirtualBox::createMachine documentation
from here:

* https://www.virtualbox.org/sdkref/interface_i_virtual_box.html

This Fixes #1322

### CODE REVIEW

**Comment by schaefi** [comment]
I knew these is going to become a source for trouble... hope it's complete this time

**Comment by schaefi** [comment]
> LGTM even I am not very happy with the hardcoded `OSType`. I guess there isn't much we can do about that, but this can strike back if in the future there is vagrant support for other architectures.
> 
> Note that I have not executed it.

Linux_64 is pretty generic and we lived with that in the template at another place already. To my knowledge the guest id only has implications on some performance tweaks done by the hypervisor. If none of those apply to a generic linux 64bit system I'm happy

**Comment by schaefi** [comment]
We will wait for Dan to come back with a test before we merge it this time ;)

**Comment by dcermak** [comment]
Doesn't work for me:
``` ShellSession
$ vagrant up --provider virtualbox
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'Tumbleweed.x86_64-1.0-virtualbox-Build.vagrant.virtualbox.box'...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "-n", "/home/dan/.vagrant.d/boxes/Tumbleweed.x86_64-1.0-virtualbox-Build.vagrant.virtualbox.box/0/virtualbox/box.ovf"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /home/dan/.vagrant.d/boxes/Tumbleweed.x86_64-1.0-virtualbox-Build.vagrant.virtualbox.box/0/virtualbox/box.ovf...
VBoxManage: error: Error in  (line 23) -- Required Machine/@uuid or @name attributes is missing.
VBoxManage: error: /home/abuild/rpmbuild/BUILD/VirtualBox-6.1.6/out/linux.amd64/release/obj/VBoxAPIWrap/ApplianceWrap.cpp[407] (virtual nsresult ApplianceWrap::Interpret())
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ApplianceWrap, interface IAppliance, callee IAppliance
VBoxManage: error: Context: "Interpret" at line 447 of file VBoxManageAppliance.cpp

```

This should be using the `box.ovf` from this PR:
``` ShellSession
$ grep -C 2 -i audio ~/.vagrant.d/boxes/Tumbleweed.x86_64/1.0.18.2/virtualbox/box.ovf
    <vbox:Machine ovf:required="false" name="Tumbleweed" OSType="Linux_64">
      <Hardware>
        <AudioAdapter enabled="false"/>
      </Hardware>
    </vbox:Machine>
```
so not sure what the issue is…

FYI: The box is from my [home project](https://build.opensuse.org/package/show/home:dancermak:branches:Virtualization:Appliances:Images:openSUSE-Tumbleweed/kiwi-images-vagrant).

**Comment by dcermak** [comment]
> LGTM even I am not very happy with the hardcoded `OSType`. I guess there isn't much we can do about that, but this can strike back if in the future there is vagrant support for other architectures.

Other architectures are not really a concern, as Virtualbox supports x86_64 only anyway (well, maybe i686, but who uses that nowadays?).

**Comment by schaefi** [comment]
I have setup a testing system again and tested that myself. uuid and <Memory> is mandatory to let virtualbox load the ovf. This PR needs changes

**Comment by schaefi** [comment]
@dcermak I've did the needed changes, the box did start now. I only tested direct virtualbox boot not through vagrant. Can you please give this another test in your env ? Thanks

**Comment by dcermak** [comment]
> @dcermak I've done the needed changes, the box did start now. I only tested direct virtualbox boot not through vagrant. Can you please give this another test in your env ? Thanks

Still broken:
``` 
==> default: Successfully added box 'Tumbleweed.x86_64' (v1.0.18.3) for 'virtualbox'!
==> default: Importing base box 'Tumbleweed.x86_64'...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "-n", "/home/dan/.vagrant.d/boxes/Tumbleweed.x86_64/1.0.18.3/virtualbox/box.ovf"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /home/dan/.vagrant.d/boxes/Tumbleweed.x86_64/1.0.18.3/virtualbox/box.ovf...
VBoxManage: error: Error in  (line 23) -- UUID "30d5a2db-01" has invalid format.
VBoxManage: error: /home/abuild/rpmbuild/BUILD/VirtualBox-6.1.6/out/linux.amd64/release/obj/VBoxAPIWrap/ApplianceWrap.cpp[407] (virtual nsresult ApplianceWrap::Interpret())
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ApplianceWrap, interface IAppliance, callee IAppliance
VBoxManage: error: Context: "Interpret" at line 447 of file VBoxManageAppliance.cpp
```

**Comment by schaefi** [comment]
invalid uuid format. In fact I haven't expected that value. Still investigating

**Comment by schaefi** [comment]
Uhm, I'm stupid rootfs uuid is wanted and I give it the partition uuid

**Comment by schaefi** [comment]
@dcermak 

```
<vbox:Machine ovf:required="false" name="Tumbleweed" uuid="20fdee27-c300-46d4-9477-4a513493c5ea" OSType="Linux_64">
```

now it will work... last famous words ;)

**Comment by schaefi** [comment]
I also added an integration test since I realized we don't have one

**Comment by dcermak** [comment]
> now it will work... last famous words ;)

*sight*
```
==> default: Importing base box 'Tumbleweed.x86_64'...
Progress: 90%There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "/home/dan/.vagrant.d/boxes/Tumbleweed.x86_64/1.0.18.4/virtualbox/box.ovf", "--vsys", "0", "--vmname", "Tumbleweed_1588181976705_45223", "--vsys", "0", "--unit", "11", "--disk", "/home/dan/VirtualBox VMs/Tumbleweed_1588181976705_45223/box.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /home/dan/.vagrant.d/boxes/Tumbleweed.x86_64/1.0.18.4/virtualbox/box.ovf...
OK.
0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Appliance import failed
VBoxManage: error: <vbox:Machine> element in OVF contains a medium attachment for the disk image  but the OVF describes no such image
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ApplianceWrap, interface IAppliance
VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 1118 of file VBoxManageAppliance.cpp

```

Did I mention that VirtualBox is "fun"?

**Comment by schaefi** [comment]
I have no idea what that means. I'm leaning towards reverting everything in that stupid ovf and go without any machine section as before. Thoughts ?

**Comment by schaefi** [comment]
what the heck is wrong ? 

```
blkid /dev/mapper/loop0p1 
/dev/mapper/loop0p1: LABEL="ROOT" UUID="68a0621a-0179-4784-ba22-5226d19df0b3" TYPE="ext4" PARTUUID="a65a5ec8-01"

<vbox:Machine ovf:required="false" name="Tumbleweed" uuid="68a0621a-0179-4784-ba22-5226d19df0b3" OSType="Linux_64">
```

That's all correct unless they want another uuid
```

**Comment by schaefi** [comment]
I found it, it's required to have StorageControllers configured

**Comment by schaefi** [comment]
@dcermak I have added a StorageController with uuid reference. That fixed the import for me.
Sorry to ask again, but could you give it yet another try ? Thanks

**Comment by schaefi** [comment]
really :) thanks much for your patience and testing :+1:

**Pull request merged**
