### PR TITLE
SUSE Documentation

### PR DESCRIPTION
**Pull request by schaefi**
The SUSE documentation is docbook or asciidoc based, none of those targets are part of the sphinx ReST documentation which we maintain in the kiwi project. Therefore we need a way to convert the ReST sources into SUSE style. This is not an easy task because the style is different at several stages. Together with Thomas Schraitle we got to a point where I think this PR makes sense.

We are not complete though and we will update this PR until it's ready for merge. As we would like to improve the documentation together with the SUSE doc team like we did it with the legacy kiwi version we need a way to contribute within the expected format but also care for the existing style and format to not upset our users upstream. With this pull request I think we are on a good way to achieve this.

I'm open for any feedback and suggestions how to solve the still open issues

### CODE REVIEW

**Comment by schaefi** [comment]
The documentation built for SUSE looks like this:

* https://w3.suse.de/~ms/kiwi/html/kiwi/index.html

**Comment by schaefi** [comment]
I noted the following issues so far:

* no title page, content of the title page is on chapters on the main index
* no sidebar which usually contains the links to the integration tests
* no section "List of Figures" which doesn't really fit in
* no table of contents for subtopics like building images -> working with images

**Comment by schaefi** [comment]
I have restructured the documentation sources in a way that should allow us to work in both styles

**Comment by schaefi** [comment]
I've update the online test page with the latest changes. Just take a look here:

* https://w3.suse.de/~ms/kiwi/html/kiwi/index.html

**Comment by schaefi** [comment]
With a lot of help from @tomschr we are now able to produce an acceptable suse doc result from the rest based doc sources :-)) Thanks much Tom a successful hackweek project.

There is only little change we need to apply to this sources and that's the reference into the custom github branch for the rstxml2docbook.git.

@tomschr can you give me a short note when you have updated the module on pip such that I can change the .virtualenv.dev-requirements file to reference rstxml2docbook from pip instead of git.

Thanks a ton

**Comment by tomschr** [comment]
> @tomschr can you give me a short note when you have updated the module on pip such that I can change the .virtualenv.dev-requirements file to reference rstxml2docbook from pip instead of git.

With "updated the module on pip" you mean probably from PyPI? I've never used PyPI for this project. :wink:  I think, it doesn't hurt to use the GitHub URL or do you see here a problem?

**Comment by schaefi** [comment]
Oh yes I see ```pip search rstxml2docbook``` doesn't match anything. Sorry not sure why but I thought it will exist on pypi.I'm ok with fetching it from the git but I think we should fetch from master or what you consider stable and not from the kiwi branch. imho all changes you did are generic or do you plan to maintain an extra kiwi branch ? Please keep in mind of we go this route your tool will become somewhat important and mandatory for us ;) Just let me know what you think. Thanks

**Comment by tomschr** [comment]
> Sorry not sure why but I thought it will exist on pypi. I'm ok with fetching it from the git but I think we should fetch from master or what you consider stable and not from the kiwi branch. 

No worries. :smile: Yes, I was thinking the same. I need probably some more time to take care of the test cases. A task which I didn't do... :blush:  Hehe, I remember our email conversation about that. :laughing: 

> imho all changes you did are generic or do you plan to maintain an extra kiwi branch ? Please keep in mind of we go this route your tool will become somewhat important and mandatory for us ;) Just let me know what you think. Thanks

I *think* they are generic enough, although you can't be really sure with RST and such a complex transformation. I'm aware of that this becomes somewhat important now. :wink: 

I would like to finish the missing test cases first, before I would like to merge it to master. Can we keep that branch for a the time being?

**Comment by schaefi** [comment]
>I would like to finish the missing test cases first, before I would like to merge it to master. Can we >keep that branch for a the time being?

yep fine by me. So we can go with the branch and you can take your time as needed. At the time you are ready with review and tests I just would like to ask you to think about the kiwi project and create a small pull request if the branch is moving away such that the doc_suse target remains working. Thanks

**Comment by tomschr** [comment]
> I just would like to ask you to think about the kiwi project and create a small pull request if the branch is moving away such that the doc_suse target remains working.

Sure, will do! :+1:

**Pull request merged**
