### PR TITLE
Add missing dependency to simplejson

### PR DESCRIPTION
**Pull request by adrianschroeter**
kiwi crashed on start without it in factory builds

### CODE REVIEW

**Comment by schaefi** [comment]
Thanks looks good to me :+1:

**Comment by schaefi** [comment]
@Conan-Kudo do you see any negative side effects ?

**Comment by schaefi** [comment]
Hmm, on a second look, there is already a requirement set to ```python%{python3_pkgversion}-simplejson```

**Review by Conan-Kudo — CHANGES_REQUESTED** [review]
This is already present in the spec file.

**Comment by adrianschroeter** [comment]
ah, sorry, a fellow co-maintainer messed this up in OBS:Server:Unstable

**Pull request closed without merging**
