### PR TITLE
Replacing LimeJeOS or JeOS by Appliance #1544

### PR DESCRIPTION
**Pull request by vmoutoussamy**
Except for build_in_buildservice.rst and python-kiwi.changes.

In a similar fashion https://github.com/OSInside/kiwi-descriptions/pull/77
Discussion happened at https://github.com/OSInside/kiwi/issues/1544

### CODE REVIEW

**Comment by schaefi** [comment]
Great work :+1: thanks a ton for helping us. I'll take a closer look soon

**Review by davidcassany — APPROVED** [review]
Thanks a lot for this PR :+1: Lets RIP LimeJeOS term

**Comment by schaefi** [comment]
I'm sorry my pull request made this one to create conflicts. I'm going to fix it

**Comment by schaefi** [comment]
@vmoutoussamy *urks* you are working from a fork so it seems I could not fix the conflict. Do you want me to move over your changes or are you ok with fixing the conflict ? I'm sorry there was no other choice as I had to touch the descriptions with regards to #1552 

Let me know what you prefer

Thanks

**Comment by schaefi** [comment]
closing with reference to #1556

**Pull request closed without merging**
