### PR TITLE
Fixed centos integration test

### PR DESCRIPTION
**Pull request by schaefi**
Currently centos images does not build because of
a broken XML description

### CODE REVIEW

**Comment by schaefi** [comment]
I also opened this PR to track the other problem for centos and fedora disk builds. The bug in grub2-install.

**Comment by schaefi** [comment]
If you build in efi firmware mode you get this error from grub2-install

[  405s] grub2-install: error: cannot rename the file /boot/grub2/grubenv.new to /boot/grub2/grubenv: No such file or directory.

There is a bug open on the rhel bugzilla. @Conan-Kudo do you have more information about the status of this issue ?

Thanks

**Comment by Conan-Kudo** [comment]
No clue... @martinezjavier or @vathpela?

**Comment by martinezjavier** [comment]
> [ 405s] grub2-install: error: cannot rename the file /boot/grub2/grubenv.new to /boot/grub2/grubenv: No such file or directory.

@schaefi @Conan-Kudo  I've seen this error in the past when the EFI System Partition (ESP) is not mounted in `/boot/efi`. Because in Fedora/RHEL/CentOS the `grubenv` file in `/boot/grub2/grubenv` is a symlink to `../efi/EFI/$efidir/grubenv`.

Can you please check that the ESP is properly mounted and that a `grubenv` file exists in `/boot/efi/EFI/centos/grubenv`? Otherwise the grub2 tools will fail if `/boot/grub2/grubenv` is a broken symlink.

Now, regardless of this issue I don't think is a good idea to execute `grub2-install` at all in EFI mode for the following reasons:

1) It calls `grub2-mkimage` which re-links the grub2 EFI binary and so the resulting binary is not signed. That means the machine won't boot with Secure Boot enabled.

For example on a Fedora machine:

```
$ pesign -S --in /boot/efi/EFI/fedora/grubx64.efi 
---------------------------------------------
certificate address is 0x7f56ee7e9008
Content was not encrypted.
Content is detached; signature cannot be verified.
The signer's common name is Fedora Secure Boot Signer
No signer email address.
Signing time: Mon Jan 13, 2020
There were certs or crls included.
---------------------------------------------

$ grub2-install /dev/vda
Installing for x86_64-efi platform.
Installation finished. No error reported.


$ pesign -S --in /boot/efi/EFI/fedora/grubx64.efi 
No signatures found.
```

2) It removes the BootEntry that was created during installation, and creates a new one that sets the file path to the unsigned grub2 EFI binary instead of shim. So again the machine will fail to boot with Secure Boot.

```
$ efibootmgr -v
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0002,0001,0000,0003
Boot0000* UiApp FvVol(7cb8bdc9-f8eb-4f34-aaea-3ee4af6516a1)/FvFile(462caa21-7614-4503-836e-8ab6f4662331)
Boot0001* UEFI Misc Device      PciRoot(0x0)/Pci(0x2,0x3)/Pci(0x0,0x0)N.....YM....R,Y.
Boot0002* Fedora        HD(1,GPT,93b1a3d1-2c2c-414d-a00c-52a8672104ab,0x800,0x12c000)/File(\EFI\fedora\shimx64.efi)
Boot0003* EFI Internal Shell    FvVol(7cb8bdc9-f8eb-4f34-aaea-3ee4af6516a1)/FvFile(7c04a583-9e3e-4f1c-ad65-e05268d0b4d1)

$ grub2-install /dev/vda
Installing for x86_64-efi platform.
Installation finished. No error reported.

$ efibootmgr -v
BootCurrent: 0002
Timeout: 0 seconds
BootOrder: 0002,0001,0000,0003
Boot0000* UiApp FvVol(7cb8bdc9-f8eb-4f34-aaea-3ee4af6516a1)/FvFile(462caa21-7614-4503-836e-8ab6f4662331)
Boot0001* UEFI Misc Device      PciRoot(0x0)/Pci(0x2,0x3)/Pci(0x0,0x0)N.....YM....R,Y.
Boot0002* fedora        HD(1,GPT,93b1a3d1-2c2c-414d-a00c-52a8672104ab,0x800,0x12c000)/File(\EFI\fedora\grubx64.efi)
Boot0003* EFI Internal Shell    FvVol(7cb8bdc9-f8eb-4f34-aaea-3ee4af6516a1)/FvFile(7c04a583-9e3e-4f1c-ad65-e05268d0b4d1)
```

3) The `grub2-install` tool isn't that tested on EFI so there are issues like the one mentioned here. 

Of course we need to fix any issues with `grub2-install` on EFI machines but that won't solve (1) and (2). So I would avoid calling for EFI if you want to support the Secure Boot case.

**Comment by schaefi** [comment]
@martinezjavier thanks much I'll check on all points you mentioned...

>Now, regardless of this issue I don't think is a good idea to execute grub2-install at all in EFI >mode for the following reasons:

You are absolutely right. For the EFI case we don't call grub2-install. But our images are hybrid in terms of bootable on EFI and BIOS. So the grub2-install call installs x86 boot code into the embedded MBR such that the image boots independent of the used firmware

**Comment by martinezjavier** [comment]
> But our images are hybrid in terms of bootable on EFI and BIOS

I see, thanks a lot for the clarification. Please let me know if you find more issues.

**Comment by schaefi** [comment]
@martinezjavier many thanks, you pointed to the right direction. It worked:

See the integration test builds:

* https://build.opensuse.org/project/show/Virtualization:Appliances:Images:Testing_x86:centos

nice :-)

Thanks again

**Comment by martinezjavier** [comment]
> @martinezjavier many thanks, you pointed to the right direction. It worked:

Great, thanks a lot for fixing it!

**Pull request merged**
