### PR TITLE
Fix appx manifest for WSL containers

### LINKED ISSUE #1780: WSL appx image in OBS required author contact as email results in invalid appx schema
## Problem description

kiwi image definition fields `author` and `contact` overwrite prepared wsl-appx metadata for `AppxManifest.xml` `Identity` `Name`. `Properties` elements `DisplayName` and `PublisherDisplayName` are also overwritten by static string `system-container`,

I am working on direct kiwi WSL appx image generation in OBS. Package `wsl-appx` provides a complete `AppxManifest.xml` and associated metadata. When kiwi image builder `kiwi-images-wsl` creates the `.appx` image, required fields `author` and `contact`:

``` xml
 <?xml version="1.0" encoding="utf-8"?>
 <image schemaversion="6.1" name="opensuse-wsl">
   <description type="system">
     <author>SUSE WSL Team</author>
     <contact>wsl@suse.com</contact>
     <specification>openSUSE WSL Image</specification>
   </description>
   <preferences>
```
overwrite the prepared `Identity` attribute `Name` with an email address:

``` diff
--- wsl-appx-input-AppxManifest.xml
+++ kiwi-wsl-images-output-AppxManifest.xml
-  <Identity Name="REDACTED.openSUSELeap15.3Beta"      Version="15.3.2645.0" Publisher="E=home:(...), CN=home:(...)" ProcessorArchitecture="x64"/>
+  <Identity Name="SUSE WSL Team &lt;wsl@suse.com&gt;" Version="15.3.2645.0" Publisher="E=home:(...), CN=home:(...)" ProcessorArchitecture="x64"/>

   <Properties>
-    <DisplayName>openSUSE Leap 15.3 Beta</DisplayName>
-    <PublisherDisplayName>SUSE</PublisherDisplayName>
+    <DisplayName>system-container</DisplayName>
+    <PublisherDisplayName>system-container</PublisherDisplayName>
```

This results in invalid character schema validation (angle brackets, spaces) when attempting to run the `.appx` image in Windows, as well as loss of the image name data prepared in package `wsl-appx` using information from file `os-release` and other informaiton. This information is necessary to publish in the Windows Store:

```
PS C:\Users\User> Add-AppxPackage .\opensuse-wsl.x86_64-1.0.0-Build29.1.appx
Add-AppxPackage : Deployment failed with HRESULT: 0x80080204, The Appx package's manifest is invalid.
error 0xC00CE169: App manifest validation error: The app manifest must be valid as per schema: Line 3, Column 15,
Reason: 'SUSE WSL Team <wsl@suse.com>' violates pattern constraint of '[-.A-Za-z0-9]+'.
The attribute 'Name' with value 'SUSE WSL Team <wsl@suse.com>' failed to parse.
```

A related unwanted substitution of data also occurs with the `Properties` elements `DisplayName` and `PublisherDisplayName` by `system-container`, as shown in the above diff. These should also be preserved verbatim for proper publishing in the Windows Store.

## Expected behaviour

- kiwi image generation for image type `appx` should not overwrite `AppxManifest.xml` element `Identity` attribute `Name`.
- The `AppxManifest.xml` schema regex for element `Identity` attribute `Name`.  `[-.A-Za-z0-9]+` which cannot use an email address.
- In this case, the overloaded term `Name` refers to a fully qualified published image identity in the Windows Store, not author identity, so these fields are not quite the correct semantic information.
- The above diff in output `AppxManifest.xml` should be eliminated for publishing the the Windows store to work.

## Steps to reproduce the behaviour

Build `kiwi-images-wsl` appx images in OBS using `AppxManifest.xml` prepared by `wsl-appx`. The OBS project configuration to implement this currently lives in ephemeral package project branches. which I can point to in comments if requested.

## OS and Software information
+ KIWI version: `python3-kiwi-9.21.23` according to `osc buildinfo -d`
+ Operating system: openSUSE Leap 15.3 Beta image target, but OBS is the build environment
+ OBS version: deployed version at build.opensuse.org as of 2021-03-19, I don't know how to check that deployment.

### PR DESCRIPTION
**Pull request by davidcassany**
This commit prevents KIWI from setting Identity Name attribute and
DisplayName and PublisherDisplayName elements.

Fixes #1780

### CODE REVIEW

**Comment by davidcassany** [comment]
@jfkw with this change KIWI won't ever modify `Name` attribute of the `Identity` element neither will set the `DisplayName` and `PoblisherDisplayName`.  Is this what is requested, is it the expected workflow that the user has no change to modify this values from the the KIWI xml description?

Also it would be great if you could give it a test to this PR

**Review by schaefi — APPROVED** [review]
The changes looks good, deleting code is always nice :smile: 

However, it should be crystal clear that this is the intention. Therefore we need feedback from the author of the report if this is the desired behavior prior merge

**Comment by jfkw** [comment]
With this change, KIWI appx image generation is working. The existing metadata in `AppxManifest.xml` is no longer overwritten. Thank you very much for the rapid fix.

**Comment by jfkw** [comment]
An addendum to the earlier success report. The `AppxManifest.xml` attribute values for `DisplayName` and `ShortName` are still being overwritten with value `system-container`:

```diff
--- wsl-appx-input-AppxManifest.xml
+++ kiwi-wsl-images-output-AppxManifest.xml
@@ -17,8 +17,8 @@
     </Capabilities>
     <Applications>
         <Application EntryPoint="Windows.FullTrustApplication" Executable="openSUSE-Leap-15.3-Beta.exe" Id="openSUSELeap153Beta">
-            <uap:VisualElements BackgroundColor="#73ba25" Description="openSUSE Leap 15.3 Beta" DisplayName="openSUSE Leap 15.3 Beta" ... >
-                <uap:DefaultTile ShortName="openSUSE Leap 15.3 Beta" ... >
+            <uap:VisualElements BackgroundColor="#73ba25" Description="openSUSE Leap 15.3 Beta" DisplayName="system-container" ... >
+                <uap:DefaultTile ShortName="system-container" ... >
                     <uap:ShowNameOnTiles>
                         <uap:ShowOn Tile="wide310x150Logo"/>
                         <uap:ShowOn Tile="square310x310Logo"/>
```

This allows the `.appx` image to be installed, but will likely prevent uploading to the Microsoft store.

This test was run using `python3-kiwi-9.23.22` (same version currently in factory), plus commit 7eac24301e08670d351f0182f3f012befb1679e2 from this PR in patch form.

Thanks again for the help.

**Comment by jfkw** [comment]
To the point about the changes in this PR matching end user expectations: I presume the [existing KIWI mechanism](https://osinside.github.io/kiwi/building_images/build_wsl_container.html?highlight=wsl#setup-of-the-wsl-distrolauncher) for supplying `AppxManifest.xml` metadata in `<containerconfig><history/></containerconfig>` will continue to work and will override any individual values supplied in the `AppxManifest.xml` file on disk at `metadata_path` ? If so, I think that will be what end users need, i.e. the ability to customize one or more specific attributes from the defaults provided by package `wsl-appx`.

**Comment by schaefi** [comment]
> To the point about the changes in this PR matching end user expectations: I presume the [existing KIWI mechanism](https://osinside.github.io/kiwi/building_images/build_wsl_container.html?highlight=wsl#setup-of-the-wsl-distrolauncher) for supplying `AppxManifest.xml` metadata in `<containerconfig><history/></containerconfig>` will continue to work and will override any individual values supplied in the `AppxManifest.xml` file on disk at `metadata_path` ? If so, I think that will be what end users need, i.e. the ability to customize one or more specific attributes from the defaults provided by package `wsl-appx`.

yes the basic concept of the overriding mechanism will stay. This pull request reduces the context of the manifest which gets touched by kiwi though.

To be more precise the following fields should no longer be touched and stay as they are provided:

```xml
<Package ...
    <Identity Name="out_of_scope"  ...
    <Properties>
        <DisplayName>out_of_scope</DisplayName
        <PublisherDisplayName>out_of_scope</PublisherDisplayName>
    ...
```

>An addendum to the earlier success report. The AppxManifest.xml attribute values for DisplayName and ShortName are still being overwritten with value ```system-container```

yes it seems the PR is not yet complete

Just to put us all right. You intentionally don't want kiwi to change the values for

* Package(Name)
* Identity/Properties/DisplayName
* Identity/Properties/PublisherDisplayName
* Applications/Application/VisualElements/DefaultTile(ShortName)

Ist that correct ?

Regarding the ShortName we set the given container name or ```system-container``` as the default container name.
I thought this would be a good setting but I must admit I don't know the exact context for which ShortName is used on
Windows.

Can you share your thoughts about ShortName and if that should be a setting that should correlate to the kiwi image description or not

Thanks

**Comment by jfkw** [comment]
Thanks for the review and summary. Yes, I think it would be best to not set `ShortName` to be the KIWI image definition `container-name` as `ShortName` is limited to between 1 and 40 characters. In `wsl-appx` we apply some targeted truncation to get a nice looking string during beta/rc phases.

Here are the current `AppxManifest.xml` templated values (`@VALUE@`) that `wsl-appx` takes responsibility for computing, and should only be overridden by user supplied values in `<containerconfig><history/></containerconfig>`:

```
<Identity Name="46932SUSE.@IDENTITYAPPID@" ProcessorArchitecture="@ARCH@" Publisher="@PUBLISHER@" Version="@VERSION@"/>
    <DisplayName>@PRETTY_NAME@</DisplayName>
    <PublisherDisplayName>@PUBLISHER_DISPLAY_NAME@</PublisherDisplayName>
     <Application Executable="@LAUNCHERNAME@" Id="@APPID@">
         <uap:VisualElements Description="@PRETTY_NAME@" DisplayName="@PRETTY_NAME@">
             <uap:DefaultTile ShortName="@SHORT_NAME@">
             <uap3:Extension Executable="@LAUNCHERNAME@">
                     <desktop:ExecutionAlias Alias="@LAUNCHERNAME@"/>
```

The `AppxManifest.xml` schema places restrictions on length and allowed characters that should not restrict other KIWI images, so it seems best to treat `<containerconfig><history/></containerconfig>` as the only interaction with `AppxManifest.xml` values, even if that means some duplication of standard KIWI image description fields.

As we gain more experience publishing to the Microsoft Store we can hopefully supply some of those constraints in a format suitable for potential inclusion in the KIWI RNG schema. Perhaps a future version of the feature would allow embedding of any validated `AppxManifest.xml` elements for image customization, beyond the currently enumerated `created_by`, `author`, `application_id`, `package_version`, and `launcher`. Customizing branding information for example may be easier for end users to accomplish in their KIWI definition than in a bespoke wsl-appx package.

### AppxManifest.xml schema excerpts

[Identity element schema](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-identity#syntax):

```
<Identity Name                   = A string between 3 and 50 characters in length that consists of alpha-numeric, period, and dash characters.
          ProcessorArchitecture? = "x86" | "x64" | "arm" | "arm64" | "neutral"
          Publisher              = A string between 1 and 8192 characters in length that fits the regular expression  of a distinguished name : "..."
          Version                = A version string in quad notation, "Major.Minor.Build.Revision" where Major cannot be "0". 
```


[DisplayName element schema](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-displayname#syntax):

```
<DisplayName>
  A string between 1 and 256 characters in length. This string is localizable. 
</DisplayName>
```

[PublisherDisplayName element schema](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-publisherdisplayname#syntax)

```
<PublisherDisplayName>
  A string between 1 and 256 characters in length. This string is localizable. 
</PublisherDisplayName>
```

The attribute `ShortName` has a length limit that the user might easily exceed the allowed 40 characters:

[uap:DefaultTile element schema](https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/uapmanifestschema/element-uap-defaulttile#syntax)

```
  ShortName?         = A string between 1 and 40 characters in length. 
```

**Comment by schaefi** [comment]
Great :+1: thanks for the details.

@davidcassany will you have a look where in the code the DisplayName is still set and to remove the ShortName handling ? or do you want me to kick in, just in case you are busy with other stuff ?

Thanks much

**Comment by davidcassany** [comment]
Hi @schaefi and @jfkw thank you both for all the details and this precise review.



> @davidcassany will you have a look where in the code the DisplayName is still set and to remove the ShortName handling ? or do you want me to kick in, just in case you are busy with other stuff ?

I'll try to find the spot today afternoon to finalize this card. I will let you know if I struggle to find the time, but it should be fine.

Thanks

**Comment by davidcassany** [comment]
@jfkw the updated PR I think now matches the expectations. Would you mind give it a try? I'm sorry I do not have any testing environment at hand by myself and I can't test it.

**Comment by jfkw** [comment]
Thank you @davidcassany , the updated PR is working perfectly. There is zero diff to the `AppxManifest.xml` put on disk by package `wsl-appx`.

Here is a visual example of where it used to display `system-container` and is now fixed:

wsl-displayname-fixed

Since this PR is purely code removal, and in a code path that only affects WSL image generation, would it be possible to push a backported change to SLE-15 tomorrow in time for the RC deadline? This would prevent a the need for branched package in each WSL image generation project.

**Comment by lkocman** [comment]
Hello team, any chance to get this in prior RC (this Wednesday 21st April) ? Thank you

**Comment by schaefi** [comment]
> Hello team, any chance to get this in prior RC (this Wednesday 21st April) ? Thank you

Thanks much David for the additional fix. I will merge the PR and provide a new kiwi in the Staging are from here: https://download.opensuse.org/repositories/Virtualization:/Appliances:/Staging/ If all tests pass a submission to Factory follows. 

Our SLES refresh cycle is every three month and there is currently a submission pending which you can follow in #1717 If you need anything in SLES earlier we need to talk

**Comment by davidcassany** [comment]
@jfkw @lkocman I was just about to point out the same @schaefi did, we just did a submission of KIWI to SLE 15 a couple of weeks ago to match some RC deadline already, I would prefer if we can just wait until the next SLE regular update cycle. If this is required earlier we need to talk about it, as will not fork KIWI across SPs, so whatever is needed in SLE we aim to push it to the SLE 15 code base and this might take some time.

**Comment by lkocman** [comment]
ah oky thanks for explanation, so then for us the importance of having the maintenance request merged is GM/GA image as this is when we'll build the final image.

**Comment by schaefi** [comment]
@lkocman yes at the time when you plan to release this change needs to be available. This means we should know about your release schedule for the WSL containers. Can you share this information ? 

> I can try to help increase priority of the maint request if needed.

Do you have a jira number which we can use as a reference for this release ? I will add that to the history and this makes it also easier to have conversations with maintenance to speedup submissions.

If you can't share this information publicly here I'd like to ask you to send the information by mail

Thanks

**Pull request merged**
